window.teamSet = [
    // strong teams
    {name: 'Real Madrid', ovr: 85, star: 5, gender: 'Men'},
    {name: 'Manchester City', ovr: 85, star: 5, gender: 'Men'},
    {name: 'FC Bayern Munchen', ovr: 84, star: 5, gender: 'Men'},
    {name: 'Liverpool', ovr: 84, star: '', gender: 'Men'},
    {name: 'FC Barcelona', ovr: 84, star: '', gender: 'Men'},
    {name: 'Arsenal', ovr: 83, star: '', gender: 'Men'},
    {name: 'Bayer 04 Leverkusen', ovr: 83, star: '', gender: 'Men'},
    {name: 'Lombardia FC (Inter)', ovr: 84, star: '', gender: 'Men'},
    {name: 'Paris Saint-Germain', ovr: 83, star: '', gender: 'Men'},
    {name: 'Atletico Madrid', ovr: 82, star: '', gender: 'Men'},
    {name: 'Chelsea', ovr: 80, star: '', gender: 'Men'},
    {name: 'Borussia Dortmund', ovr: 81, star: '', gender: 'Men'},
    {name: 'Milano (AC Milan)', ovr: 81, star: '', gender: 'Men'},

    // mid teams
    {name: 'Manchester United', ovr: 80, star: 4.5, gender: 'Men'},
    {name: 'Aston Villa', ovr: 81, star: '', gender: 'Men'},
    {name: 'Newcastle United', ovr: 81, star: '', gender: 'Men'},
    {name: 'RB Leipzig', ovr: 80, star: '', gender: 'Men'},
    {name: 'Juventus', ovr: 80, star: '', gender: 'Men'},
    {name: 'Roma', ovr: '', star: '', gender: 'Men'},
    {name: 'Athletic Club', ovr: '', star: '', gender: 'Men'},
    {name: 'West Ham United', ovr: '', star: '', gender: 'Men'},
    {name: 'Bergamo Calcio', ovr: '', star: '', gender: 'Men'},
    {name: 'Latium (Lazio)', ovr: 79, star: '', gender: 'Men'},
    {name: 'Napoli', ovr: 79, star: '', gender: 'Men'},
    {name: 'Galatasaray SK', ovr: '', star: '', gender: 'Men'},
    {name: 'Fenerbahce SK', ovr: 80, star: '', gender: 'Men'},
    {name: 'Girona FC', ovr: '', star: '', gender: 'Men'},
    {name: 'Crystal Palace', ovr: '', star: '', gender: 'Men'},
    {name: 'Brighton & Hove Albion', ovr: '', star: '', gender: 'Men'},
    {name: 'Fiorentina', ovr: '', star: '', gender: 'Men'},
    {name: 'Al Hilal', ovr: '', star: '', gender: 'Men'},
    {name: 'Real Sociedad', ovr: '', star: '', gender: 'Men'},
    {name: 'Sporting CP', ovr: '', star: '', gender: 'Men'},
    {name: 'PSV', ovr: '', star: '', gender: 'Men'},
    {name: 'Nottingham Forest', ovr: '', star: '', gender: 'Men'},
    {name: 'Olympique Lyonnais', ovr: '', star: '', gender: 'Men'},
    {name: 'Wolverhampton Wanderers', ovr: '', star: '', gender: 'Men'},
    {name: 'Fulham FC', ovr: '', star: '', gender: 'Men'},
    {name: 'Olympique de Marseille', ovr: '', star: '', gender: 'Men'},
    {name: 'Sevilla FC', ovr: '', star: '', gender: 'Men'},
    {name: 'FC Porto', ovr: '', star: '', gender: 'Men'},
    {name: 'Everton', ovr: '', star: '', gender: 'Men'},
    {name: 'Al Nassr', ovr: '', star: '', gender: 'Men'},
    {name: 'Brentford', ovr: '', star: '', gender: 'Men'},
    {name: 'AFC Bournemouth', ovr: '', star: '', gender: 'Men'},
    {name: 'VFL Wolfsburg', ovr: '', star: '', gender: 'Men'},
    {name: 'Ajax', ovr: '', star: '', gender: 'Men'},
    {name: 'Southampton', ovr: '', star: '', gender: 'Men'},
    {name: 'Leicester City', ovr: '', star: '', gender: 'Men'},
    {name: 'Tottenham Hotspur', ovr: 81, star: '', gender: 'Men'},

    // weak teams
    {name: 'Leeds United', ovr: '', star: '', gender: 'Men'},
    {name: 'Inter Miami', ovr: '', star: '', gender: 'Men'},
    {name: 'Rangers FC', ovr: '', star: '', gender: 'Men'},
    {name: 'Ipswich Town', ovr: '', star: '', gender: 'Men'},
    {name: 'Burnley', ovr: '', star: '', gender: 'Men'},
    {name: 'Los Angeles FC', ovr: '', star: '', gender: 'Men'},
    {name: 'Shakhtar Donetsk', ovr: '', star: '', gender: 'Men'},
    {name: 'RCD Espanyol', ovr: '', star: '', gender: 'Men'},
    {name: 'Genoa', ovr: '', star: '', gender: 'Men'},
    {name: 'Racing Club', ovr: '', star: '', gender: 'Men'},
    {name: 'Luton Town', ovr: '', star: '', gender: 'Men'},
    {name: 'Viktoria Plzeň', ovr: '', star: '', gender: 'Men'},
    {name: 'FC Twente', ovr: '', star: '', gender: 'Men'},
    {name: 'LA Galaxy', ovr: '', star: '', gender: 'Men'},
    {name: 'Sheffield United', ovr: '', star: '', gender: 'Men'},
    {name: 'Norwich City', ovr: '', star: '', gender: 'Men'},
    {name: 'Middlesbrough', ovr: '', star: '', gender: 'Men'},
    {name: 'Sunderland', ovr: '', star: '', gender: 'Men'},
    {name: 'West Bromwich Albion', ovr: '', star: '', gender: 'Men'},
    {name: 'Cardiff City', ovr: '', star: '', gender: 'Men'},
    {name: 'FC Cincinnati', ovr: '', star: '', gender: 'Men'},
    {name: 'FC Lorient', ovr: '', star: '', gender: 'Men'},

    // international teams
    {name: 'England', ovr: '85', star: '', gender: 'International'},
    {name: 'Portugal', ovr: '83', star: '', gender: 'International'},
    {name: 'France', ovr: '85', star: '', gender: 'International'},
    {name: 'Germany', ovr: '84', star: '', gender: 'International'},
    {name: 'Spain', ovr: '84', star: '', gender: 'International'},
    {name: 'Netherlands', ovr: '83', star: '', gender: 'International'},
    {name: 'Argentina', ovr: '83', star: '', gender: 'International'},
    {name: 'Italy', ovr: '82', star: '', gender: 'International'},

    //women teams
    {name: 'Chelsea', ovr: '85', star: '', gender: 'Women'},
    {name: 'Arsenal', ovr: '', star: '', gender: 'Women'},
    {name: 'Manchester United', ovr: '', star: '', gender: 'Women'},
    {name: 'Manchester City', ovr: '', star: '', gender: 'Women'},
    {name: 'FC Barcelona', ovr: '', star: '', gender: 'Women'},
    {name: 'Olympique Lyonnais', ovr: '', star: '', gender: 'Women'},
    {name: 'FC Bayern Munchen', ovr: '', star: '', gender: 'Women'},
    {name: 'Real Madrid', ovr: '', star: '', gender: 'Women'},
    {name: 'VFL Wolfsburg', ovr: '', star: '', gender: 'Women'},
    {name: 'Paris Saint-Germain', ovr: '', star: '', gender: 'Women'}
];

// {name: '',ovr: , star: }